### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by jomo**
Now it renders nicely on GitHub. You're also able to link to parts of the README now.

### CODE REVIEW

**Comment by slang800** [comment]
:+1:

**Comment by remram44** [comment]
Interestingly, the paypal link is missing

> You  can  pay  by  visiting  the  link  below  and  clicking on "Donate", or use this reference for donations:

**Comment by jomo** [comment]
@remram44 there was no "Donate" link in the first place, I just renamed the file

**Comment by remram44** [comment]
@jomo: yes this is unrelated to your change, just saying...

**Comment by jomo** [comment]
This was fixed by @dtrace4linux in @913ba6f961c601e5930f55f8b0bd0237ae6b3f40.

**Comment by remram44** [comment]
Paypal link is STILL missing.

**Comment by jomo** [comment]
That is STILL not related to this PR at all ;)

**Comment by remram44** [comment]
\**sigh*\* **fine...**

**Pull request closed without merging**
